### ISSUE TITLE
Noto Sans Hebrew Does Not Render Sof Pasuq Correctly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#245]
```
What steps will reproduce the problem?
1. In a browser, open http://owen0003.x10.mx/notobug.htm
2.
3.

What is the expected output? What do you see instead?
The Hebrew text on the page which uses Noto Sans should match the Hebrew text 
which uses Times New Roman.
Instead, in the Noto Sans display, sof-pasuq, which should render as a separate 
character, is overlaying the previous character, as if it were a diacritic 
rather than a punctuation mark.


What version of the product are you using? On what operating system?
Using current version of webfont using instructions on Google Fonts Early 
Access page http://www.google.com/fonts/earlyaccess .
The problem shows up in Windows 7, Windows Server 2003, and Ubuntu 12.04 LTS, 
using a variety of browsers. 


Please provide any additional information below.
Sent a notification of this bug to the appropriate mailing list; a reply asked 
me to open up a ticket here.


```

Original issue reported on code.google.com by `eclipsec...@gmail.com` on 30 Jan 2015 at 4:45

**Comment by behdad** [comment]
cc @roozbehp

**Comment by behdad** [comment]
cc @kuettel @davelab6

**Comment by nyshadhr9** [comment]
Noto Sans Hebrew on Google Fonts Early Access has been updated to the latest version. This update fixes the reported issue.

**Comment by eladkarako** [comment]
**I've solved it by adding the following to my website's main CSS file:**

```css
html,input,textarea{  font-family: 'Noto Sans', 'Roboto', sans-serif;  }

 :lang(he),:lang(he-IL)
,[lang^="hebrew"],[lang^="Hebrew"]
,[language^="hebrew"],[language^="Hebrew"]
,:lang(he-iw),[lang^="iw"],[lang^="IW"] /*old Hebrew definition was 'iw' instead of 'he' (still IS in 'IE'<9)*/
{  /*when the content is unambiguously-specified to Hebrew, *respect it*, and prefer a variation of Hebrew-font first (but still including the default ones.. later...) */
  font-family: 'Noto Sans Hebrew', 'Open Sans Hebrew', 'Tahoma', 'Adobe Hebrew', 'Alef', 'Noto Sans', 'Roboto', sans-serif;                    }
}

pre,code,kbd{         font-family: 'Noto Mono', 'Roboto Mono', 'Courier New', monospace; }
```

It should 'cover your bases' with the most of the fonts, that includes the complete Hebrew-glyph required for correct displaying Hebrew-characters mixed with other languages.

<sub>took it from: [iCompile- _CSS Snippet – A Language Specific font-family Rule That Does Not Suck!_](http://icompile.eladkarako.com/css-snippet-language-specific-font-family/)
